Add github workflows for linting, testing, building, and publishing
y-scope/clp-loglib-py pull request #32
Opened 2023-06-30 08:11 UTC by davidlion

# Description
Adds two github workflows:
1. package.yaml
    * runs all linters: docformatter, black, ruff, mypy
    * runs all unittests
    * builds the package
2. release.yaml
    * on tag push (starting with 'v') will release on pypi
    * depends on package.yaml passing

This PR also adds a few small tweaks:
* introduces the `ruff` linter
* minor improvements to satisfy ruff and mypy
* moves optional dependencies into `dev` and `test` tags in `pyproject.toml`
    * updates README.md accordingly

# Validation performed
Ran all workflows on fork and uploaded to personal test.pypi user/project.

2023-07-10 04:00 UTC, LinZhihao-723 reviewed
Add some comments

2023-07-10 04:00 UTC, LinZhihao-723 commented on .github/workflows/package.yaml
> +    runs-on: ubuntu-latest
Since we have users running this library on macos, I think we can add macos as the test host as well: `macos-latest`

2023-07-10 04:00 UTC, LinZhihao-723 commented on README.md
> +* [ruff][8]: `ruff check src tests`
According to the tutorial, we can use `--fix` option to automatically fix small errors (such as unused import). This might be helpful.

2023-07-10 04:00 UTC, LinZhihao-723 commented on README.md
>  2. Install development dependencies:
This will not install the dev dependencies but also this project. As a result, you will have clp_logging installed inside the site package. This is probably ok, but we'd better explicitly mention it.

2023-07-10 04:00 UTC, LinZhihao-723 commented on README.md
> +   `pip install .[test]`
Similar to the above. If someone modifies the code later, it will not directly reflect on the installed package since it's not installed with `-e` option. The package installed to the site package will be used instead.
Maybe we say to install with `-e` if we want the changes to be reflective. (also, we should mention `pip install --upgrade pip` to enable `-e` option. I've seen a lot of cases where the default version of `pip` doesn't support `pip install -e .` from `pyproject`)

2023-07-13 05:52 UTC, kirkrodrigues requested changes

2023-07-13 05:52 UTC, kirkrodrigues commented on pyproject.toml
> +version = "0.0.11-alpha"
I guess `-alpha` here is meant to function like `-SNAPSHOT` in Java packages? If so, is `-alpha` a Python convention?

2023-07-13 05:52 UTC, kirkrodrigues commented on .github/workflows/release.yaml
> +name: Upload package to pypi
µnit
```suggestion
name: Upload package to PyPI
```

2023-07-13 05:52 UTC, kirkrodrigues commented on .github/workflows/release.yaml
> +  # https://docs.pypi.org/trusted-publishers/using-a-publisher/
Nit: Can we add a newline before this line? That looks nicer to me since we have a comment before the `pypi-publish` block.

2023-07-13 05:52 UTC, kirkrodrigues commented on .github/workflows/release.yaml
> +      - if: ${{ 'y-scope' != github.repository_owner }}
Let's name this and the next step so that they have different names in the [GitHub UI](https://github.com/davidlion/clp-loglib-py/actions/runs/5425931460/jobs/9867365796).

2023-07-13 05:52 UTC, kirkrodrigues commented on tests/test_handlers.py
> +    :parm: target_pid pid of target process
```suggestion
    :param target_pid: pid of target process
```

2023-07-13 05:52 UTC, kirkrodrigues commented on tests/test_handlers.py
> +    with WNOHANG. If waitpid has not returned the target_pid after roughly 16s,
"16s" has a high likelihood of going out of sync with the code. How about "after some delay" or something similar?

2023-07-13 05:52 UTC, kirkrodrigues commented on tests/test_handlers.py
> +    :return: process exit code (0 on success) or 137 (128 + 9) on sigkill
What's the significance of 137?

2023-07-13 05:52 UTC, kirkrodrigues commented on tests/test_handlers.py
> +                delay + delta_s,  # delay + soft delta
Instead of using comments to describe what the variables are, why not rename the variables to reflect the comments?

2023-07-13 05:52 UTC, kirkrodrigues commented on .github/workflows/package.yaml
> +          .[dev,test]
Why do we need `test` for building?

2023-07-13 06:50 UTC, kirkrodrigues approved these changes

2023-07-13 06:55 UTC, merged