Add a `Motivation` section in README to explain the problem solved by CLP IR.
y-scope/clp-loglib-py pull request #38
Opened 2023-12-02 22:22 UTC by LinZhihao-723

# Description
As `clp-ffi-py` is developed, there are more details we can discuss in terms of CLP IR. This PR clarifies the problem CLP IR solved and the benefit of using our logging library.

2023-12-08 23:38 UTC, davidlion requested changes

2023-12-08 23:38 UTC, davidlion commented on README.md
> +format, achieving both data streaming capability and effective compression ratios. Log files
```suggestion
format, achieving both data streaming capabilities and effective compression ratios. Log files
```

2023-12-08 23:38 UTC, davidlion commented on README.md
> +serialized using IR format can be viewed using [YScope Log Viewer][2]. They can also be deserialized
```suggestion
serialized using the IR format can be viewed using the [YScope Log Viewer][2]. They can also be deserialized
```

2023-12-09 20:02 UTC, kirkrodrigues requested changes

2023-12-09 20:02 UTC, kirkrodrigues commented on README.md
> +Important Update: The readers and all the other non-logging APIs currently available in this library
Can use GitHub markdown [alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts).

2023-12-09 20:02 UTC, kirkrodrigues commented on README.md
> +search capabilities, please check and install [clp-ffi-py][9].
```suggestion
are scheduled for deprecation in an upcoming release. To access our newest and improved CLP IR
analytics interface (which offers advanced features like high-performance decoding and enhanced query
search capabilities) check out [clp-ffi-py][9].
```

2023-12-09 20:02 UTC, kirkrodrigues commented on README.md
> +[9]: https://github.com/y-scope/clp-ffi-py
Finish files with empty lines.

2023-12-09 20:02 UTC, kirkrodrigues commented on README.md
> +first encoded into the IR format, and then appended to a compressed output stream. This approach not
```suggestion
Intermediate Representation (IR) format. A log event created with a CLP logging handler will first
be encoded into the IR format, and then appended to a compressed output stream. This approach not
```

2023-12-10 00:13 UTC, kirkrodrigues requested changes

2023-12-10 00:13 UTC, kirkrodrigues commented on README.md
> +> enhanced query search capabilities) check out [clp-ffi-py][9].
```suggestion
> The readers and all the other non-logging APIs currently available in this library are scheduled
> for deprecation in an upcoming release. To access our newest and improved CLP IR analytics
> interface (which offers advanced features like high-performance decoding and enhanced query search
> capabilities) check out [clp-ffi-py][9].
```

2023-12-10 00:35 UTC, kirkrodrigues approved these changes

2023-12-10 18:57 UTC, davidlion approved these changes

2023-12-10 19:09 UTC, merged